name: YT Music PO Token Generator
version: 1.2.2
slug: ytm_po_token_generator
description: A HA addon wrapper for the BgUtils POT Provider that can generate PO tokens for Youtube Music.
url: https://github.com/Brainicism/bgutil-ytdlp-pot-provider
image: brainicism/bgutil-ytdlp-pot-provider
arch:
  - amd64
  - aarch64
ports:
  "4416/tcp": 4416
